# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'autogui_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 644)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 791, 191))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.delete_shortcut = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.delete_shortcut.setEnabled(True)
        self.delete_shortcut.setObjectName("delete_shortcut")
        self.gridLayout.addWidget(self.delete_shortcut, 0, 1, 1, 1)
        self.add_shortcut = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.add_shortcut.setObjectName("add_shortcut")
        self.gridLayout.addWidget(self.add_shortcut, 0, 0, 1, 1)
        self.set_delay = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.set_delay.setObjectName("set_delay")
        self.gridLayout.addWidget(self.set_delay, 1, 1, 1, 1)
        self.start_program = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.start_program.setObjectName("start_program")
        self.gridLayout.addWidget(self.start_program, 1, 0, 1, 1)
        self.get_info_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.get_info_button.setObjectName("get_info_button")
        self.gridLayout.addWidget(self.get_info_button, 0, 2, 1, 1)
        self.csv_parse_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.csv_parse_button.setObjectName("csv_parse_button")
        self.gridLayout.addWidget(self.csv_parse_button, 1, 2, 1, 1)
        self.shortcuts_view = QtWidgets.QTableView(self.centralwidget)
        self.shortcuts_view.setGeometry(QtCore.QRect(0, 190, 791, 361))
        self.shortcuts_view.setObjectName("shortcuts_view")
        self.error_label = QtWidgets.QLabel(self.centralwidget)
        self.error_label.setGeometry(QtCore.QRect(6, 556, 781, 41))
        self.error_label.setStyleSheet("color:rgb(224, 27, 36)")
        self.error_label.setTextFormat(QtCore.Qt.AutoText)
        self.error_label.setAlignment(QtCore.Qt.AlignCenter)
        self.error_label.setIndent(0)
        self.error_label.setObjectName("error_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.delete_shortcut.setText(_translate("MainWindow", "Delete shortcut"))
        self.add_shortcut.setText(_translate("MainWindow", "Add Shortcut"))
        self.set_delay.setText(_translate("MainWindow", "Set Delay"))
        self.start_program.setText(_translate("MainWindow", "Start Program"))
        self.get_info_button.setText(_translate("MainWindow", "Info"))
        self.csv_parse_button.setText(_translate("MainWindow", "Save to .csv"))
        self.error_label.setText(_translate("MainWindow", "ERROR 404"))
